export const profileSettingsConfig = {
  employee: {
    fullName: "Omar Haddad",
    jobTitle: "Senior Product Analyst",
    employeeId: "EMP-2026-894",
    directManager: "Layla Nasser",
    workLocation: "Downtown Campus · Tower B",
    workEmail: "omar.haddad@wisework.com",
    phone: "+971 50 123 4567",
    biometricLogin: true,
    pushNotifications: true,
  },
  admin: {
    fullName: "Ahmed Nasser",
    jobTitle: "System Administrator",
    employeeId: "ADM-2026-001",
    directManager: "Board of Directors",
    workLocation: "Headquarters · Floor 4",
    workEmail: "ahmed@wisework.io",
    phone: "+971 50 987 6543",
    biometricLogin: true,
    pushNotifications: true,
  },
  hr: {
    fullName: "Mostafa Khalil",
    jobTitle: "HR Director",
    employeeId: "HR-2026-012",
    directManager: "Ahmed Nasser",
    workLocation: "Headquarters · Floor 3",
    workEmail: "mostafa@wisework.io",
    phone: "+971 50 456 7890",
    biometricLogin: true,
    pushNotifications: true,
  },
  manager: {
    fullName: "Layla Hassan",
    jobTitle: "Engineering Manager",
    employeeId: "MGR-2026-045",
    directManager: "Ahmed Nasser",
    workLocation: "Downtown Campus · Tower A",
    workEmail: "layla@wisework.io",
    phone: "+971 50 234 5678",
    biometricLogin: true,
    pushNotifications: true,
  },
};